"""Provided constants — the agent's brain, given to you.

You do NOT edit this file in the workshop. Your job is in `agent.py`: wire these
values into the Claude Managed Agents SDK (create the agent + environment, run and
resume a cloud session). This file just holds *what* the agent is:

  * MODEL         — which Claude model runs the agent loop.
  * SYSTEM_PROMPT — how the agent should investigate an incident.
  * TOOLS         — the three custom tools it may call (your `handle_tool` in agent.py
                    answers these locally using observatory/tools.py).
"""

# Any Claude model id works. Opus is the default; "claude-sonnet-5" is cheaper.
MODEL = "claude-sonnet-5"

AGENT_NAME = "incident-detective"

SYSTEM_PROMPT = """You are an incident-investigation assistant for an observability platform.
A user gives you an incident (often just "why did X start erroring around <time>?").
Your job is to find the most likely root cause by correlating three sources of evidence.

Work in this order and use your tools — do not guess from prior knowledge:

1. Call `analyze_logs` first. Identify: when the error spike started, which service is
   failing, the upstream dependency it is failing to reach, and the top error signatures.
2. Call `list_deployments` and `git_log`. Look for a deployment or commit that landed
   shortly BEFORE the spike started AND involves the failing service or its upstream
   dependency.
3. Correlate on two axes at once — TIME (just before the spike) and BLAST RADIUS (the
   affected service or the dependency it calls). A change that is close in time but to an
   unrelated service, or to the right service but hours earlier, is probably a red herring.

Then answer with:
- The single most likely root cause: name the service, version, and commit sha, with the
  timestamps that tie it to the error spike.
- A one-line explanation of WHY it fits (connect the commit's change to the error signature).
- The other recent deploys/commits you considered and why you ruled each out.

Be concrete and cite timestamps. If the evidence is genuinely ambiguous, say so."""

TOOLS = [
    {
        "type": "custom",
        "name": "analyze_logs",
        "description": (
            "Analyze the incident log loaded in the platform. Returns the error/warn "
            "counts, when the error spike started, the affected service, the upstream "
            "dependency involved, and the top error signatures. Call this FIRST to scope "
            "the incident. Takes no input."
        ),
        "input_schema": {"type": "object", "properties": {}, "required": []},
    },
    {
        "type": "custom",
        "name": "list_deployments",
        "description": (
            "List recent service deployments (timestamp, service, version, commit, status). "
            "Use it to find a deploy that landed just before an error spike. Optional "
            "`since_minutes` controls the lookback window (default 90)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "since_minutes": {
                    "type": "integer",
                    "description": "How many minutes back to look. Default 90.",
                }
            },
            "required": [],
        },
    },
    {
        "type": "custom",
        "name": "git_log",
        "description": (
            "List recent commits (timestamp, service, sha, author, message). Optionally "
            "filter by `service` to focus on the failing service or its upstream "
            "dependency. `since_minutes` controls the lookback window (default 120)."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "description": "Only return commits for this service.",
                },
                "since_minutes": {
                    "type": "integer",
                    "description": "How many minutes back to look. Default 120.",
                },
            },
            "required": [],
        },
    },
]
